### ISSUE TITLE
Quick question: format of sourcelist

### ISSUE THREAD

**Issue by Alfiegerner** [jonaseickhoff/hass-multiroom-mqtt-mediaplayer#3]
Hi - thanks for this, I've been using it cobble together a frankenstein media system I've set up. :)

What format should the sourcelist_topic be in?, should I publish something like  `[SkyTV, AndroidTV,Kodi]` - not entirely sure on ticks / apostrophes required here.

Thanks!

**Comment by jonaseickhoff** [comment]
Hi - this should be in double quotation marks as an array in JSON objects. My musiccast bridge sends something like this: 

`["Napster","Spotify","Qobuz","TIDAL","Deezer","Amazon Music","Alexa","AirPlay","MC Link","Server","Net Radio","Bluetooth"]`

The values should match with the currently selected on "source_topic" and with the ones you select per "select_source"

**Comment by Alfiegerner** [comment]
Lovely, thanks you very much.
