### ISSUE TITLE
Background cmd

### ISSUE THREAD

**Issue by tv4you2016** [jonaseickhoff/hass-multiroom-mqtt-mediaplayer#4]
hello, thank you in advance for your nice work on the hass-multiroom-mqtt-mediaplayer dev. I have a little doubt.
You say it is compatible with mini-media-player, but I can't set the mini-media-player background, I've tested all mqtt commands from multiroom-mqtt-mediaplayer and nothing. Could you tell me which mqtt (multiroom-mqtt-mediaplayer) command does the background change in mini-media-player

**Comment by jonaseickhoff** [comment]
What do you mean with "mini-media-player background" if you mean the background image (albumart) then the image is set by "albumart_url_topic" or "albumart_topic". The "albumart_url_topic" should be an url pointing at an image, and the "albumart_topic" should be the image as base64 encoded string.
